title: Leo Bauer
url: "astonishing-speculoos-e62703.netlify.app"
baseurl: "/index"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
