title: Leo Bauer
url: "astonishing-speculoos-e62703.netlify.app"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "2023 Leo Bauer."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "Research"
   link: "research"
 - name: "Teaching"
   link: "teaching"
 - name: "Contact"
   link: "contact"
